name: Windows Logger Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allows manual run

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create bin directory
      run: mkdir bin

    - name: Compile source files
      run: |
        cl /nologo /W3 /D_CRT_SECURE_NO_WARNINGS ^
          src\main.c ^
          src\engine\core\logger.c ^
          /I src ^
          /Fe:bin\rcadia.exe

    - name: Run rcadia.exe
      run: .\bin\rcadia.exe

