name: Windows Logger Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allows manual run

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Create bin directory
      shell: cmd
      run: mkdir bin

    - name: Compile source files
      shell: cmd
      run: |
        cl /nologo /W3 /D_CRT_SECURE_NO_WARNINGS ^
          src\main.c ^
          src\engine\core\logger.c ^
          /I src ^
          /Fe:bin\rcadia.exe

    - name: Run rcadia.exe
      shell: cmd
      run: .\bin\rcadia.exe

